### ISSUE TITLE
"Can't Concat NoneType to bytearray" on sjson.loads

### ISSUE THREAD

**Issue by micriley** [Anteru/sjson#1]
```
Sjson block:
{
  Animations = [
    {
      Name = "BootImage"
      ChainTo = "BootFade"
      FilePath = "Launch\load_bg"
      Type = "Constant"
      EndFrame = 1
      NumFrames = 1
      StartFrame = 1
      Material = "Unlit"
    }
  ]
}

Simple python test:
if '__main__' == __name__:
    sjsonObj = sjson.loads(open("LaunchAnimations.sjson",encoding='utf-8').read()) 
    print (sjsonObj)
Stack Error trace:
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    sjsonObj = sjson.loads(open("LaunchAnimations.sjson",encoding='utf-8').read())
  File "C:\Users\micri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sjson\__init__.py", line 394, in loads
    return _decode_dict(MemoryInputStream(text.encode('utf-8')))
  File "C:\Users\micri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sjson\__init__.py", line 326, in _decode_dict
    value = _parse(stream)
  File "C:\Users\micri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sjson\__init__.py", line 377, in _parse
    return _parse_list(stream)
  File "C:\Users\micri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sjson\__init__.py", line 346, in _parse_list
    value = _parse(stream)
  File "C:\Users\micri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sjson\__init__.py", line 369, in _parse
    return _decode_dict(stream, True)
  File "C:\Users\micri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sjson\__init__.py", line 326, in _decode_dict
    value = _parse(stream)
  File "C:\Users\micri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sjson\__init__.py", line 371, in _parse
    return _decode_string(stream)
  File "C:\Users\micri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sjson\__init__.py", line 263, in _decode_string
    result += _decode_escaped_character(stream.read())
TypeError: can't concat NoneType to bytearray

The current index points to the last doublequote character of this line: FilePath = "Launch\load_bg", so maybe there's an issue with the backslash character? This file loads in a C# lua parser with no issue.

**Comment by Anteru** [comment]
This assumes \l is an escape sequence, and then bails out because it isn't a valid escape sequence. I've prepared a fix which simply returns it "unparsed". If you could please give the latest version a try and confirm it works for you, then I can prepare a new release with this fix.
